### ISSUE TITLE
Not Working - 8.10.9

### ISSUE THREAD

**Issue by jasonlones** [ctsit/qr_code_shortcut#10]
QR Code Shortcut does not seem to work on 8.10.9.

**Comment by marlycormar** [comment]
We have released a new version to the RC community: `v1.1.1`. Could you please test you don't experience the same issues?

**Comment by jasonlones** [comment]
Looks good to me.  Thanks!

Jason Lones
IT Analyst, Sr.
Duke Office of Clinical Research (DOCR)
School of Medicine
Phone: (919) 668-1787
